name: Miasm regression tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['2.7', '3.6', '3.8']

    steps:

    - name: Git checkout
      uses: actions/checkout@v2

    - name: Use Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Update pip
      run: pip install pip --upgrade

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Install optional requirements
      run: pip install -r optional_requirements.txt

    - name: Install test requirements
      run: pip install -r test_requirements.txt

    - name: Install llvm
      run: sudo apt-get install llvm

    - name: Install Miasm
      uses: ./.github/actions/install

    - name: Tests
      run: cd test; pytest -n auto && git ls-files -o --exclude-standard

    - name: Loader tests
      run: cd example/loader; python --version |& grep -q "Python 3" || flags="-W error"; for i in ../../miasm-extended-tests/loader/dll_win_xp/*.dll; do python get_exports.py $i; done
      env:
        MIASM_EXTENTED_TESTS_LOADER: loader

    - name: Loader tests
      run: cd "miasm-extended-tests/$MIASM_EXTENTED_TESTS_LOADER" && ./test_dll.py
      env:
        MIASM_EXTENTED_TESTS_LOADER: loader

    - name: IR tests
      run: cd "miasm-extended-tests/$MIASM_EXTENTED_TESTS_IR" && ./run.sh
      env:
        MIASM_EXTENTED_TESTS_IR: ir_tests
